### ISSUE TITLE
Strange side effect, some scss source files end up in sitemap

### ISSUE THREAD

**Issue by bobmonsour** [5t3ph/eleventy-plugin-sass-lightningcss#2]
This is really odd. I am using the plugin as directed and it generates the proper single css file that is autoprefixed and minified and my site works fine.

However, my sitemap, generated by a

```
{% for page in collections.all %}
```

ends up including links to several (but not all) of my source scss files. Here's one example:

```
        <url>
            <loc>https://www.bobmonsour.com/css/_reset.css</loc>
            <lastmod>2023-02-03T05:34:28.610Z</lastmod>
        </url>
```

My main.scss has 4 @use commands to "import" 4 scss files.

Is there some side effect where the plugin generates some collection items?

Here's a link to my repo:

https://github.com/bobmonsour/bobmonsour.com

I hope that makes some sense...but it's really odd.

**Comment by bobmonsour** [comment]
I have created a version of the eleventy-base blog to better document the issue. 

Here is [that repo](https://github.com/bobmonsour/eleventy-base-blog-main). The README of the repo better documents how I recreated the problem.

That might be simpler to examine than my blog.

In the mean time, I am going to revert my blog back to using an earlier method of sass processing with postcss.

**Comment by bobmonsour** [comment]
I just created a [branch of that repo](https://github.com/bobmonsour/eleventy-base-blog-main/tree/nolightning) that removes the lightningcss processing and only does the sass processing and I get the same result, i.e., strange items in the sitemap.

**Comment by bobmonsour** [comment]
I've moved this issue over to a discussion item on the eleventy repo [#2850](https://github.com/11ty/eleventy/discussions/2850). I'll come back here with any answer I get.

**Comment by 5t3ph** [comment]
hi @bobmonsour - thanks for filing that, I commented there with the temp solution which I'm in-progress adding to the README here.

**Comment by 5t3ph** [comment]
README updated, closing as that's the best we can do for now but I definitely have this on my radar to update if/when there is a better core solution to use.
